import { useEffect, useState } from 'react';
import { Sidebar } from '../components/Sidebar';
import { useParams, Link } from 'react-router';
import { Download, ArrowLeft, Mail, Phone, Calendar, Star } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { getLeadById } from '../api/leads';
import jsPDF from 'jspdf';

export default function PdfPreview() {
  const { id } = useParams();
  
  const { data: leadData, isLoading: loading } = useQuery({
    queryKey: ['lead', id],
    queryFn: () => getLeadById(parseInt(id!)),
    enabled: !!id
  });

  const handleDownload = () => {
    if (!leadData) return;

    const safeStr = (v: any) => (v === null || v === undefined ? '' : String(v));
    const safeStageLabel = (stage: any) => {
      const s = safeStr(stage).trim();
      if (!s) return '—';
      return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
    };
    const safeCurrency = (v: any) => (Number(v) || 0).toLocaleString('en-IN');

    const doc = new jsPDF();

    // Header
    doc.setFontSize(24);
    doc.setTextColor(0, 212, 170); // Teal
    doc.text('Lead Link CRM', 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Gray
    doc.text('Customer Relationship Management', 20, 27);

    // Report Date
    doc.setFontSize(10);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 150, 20);

    // Customer Information Section
    doc.setFontSize(16);
    doc.setTextColor(26, 35, 50); // Navy
    doc.text('Customer Information', 20, 45);

    doc.setDrawColor(209, 213, 219);
    doc.line(20, 48, 190, 48);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);

    doc.text('Company:', 20, 58);
    doc.setTextColor(26, 35, 50);
    doc.text(safeStr(leadData.company), 60, 58);

    doc.setTextColor(100, 116, 139);
    doc.text('Contact:', 20, 68);
    doc.setTextColor(26, 35, 50);
    doc.text(safeStr(leadData.contact), 60, 68);

    doc.setTextColor(100, 116, 139);
    doc.text('Email:', 20, 78);
    doc.setTextColor(26, 35, 50);
    doc.text(safeStr(leadData.email), 60, 78);

    doc.setTextColor(100, 116, 139);
    doc.text('Lead Score:', 20, 88);
    doc.setTextColor(26, 35, 50);
    doc.text(`${Number((leadData as any).leadScore) || 0}/100`, 60, 88);

    doc.setTextColor(100, 116, 139);
    doc.text('Risk Status:', 20, 98);
    doc.setTextColor(26, 35, 50);
    doc.text((leadData as any).risk ? safeStr((leadData as any).risk).toUpperCase() : 'LOW', 60, 98);

    // Deal Information Section
    doc.setFontSize(16);
    doc.setTextColor(26, 35, 50);
    doc.text('Deal Information', 20, 115);

    doc.line(20, 118, 190, 118);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);

    doc.text('Deal Value:', 20, 128);
    doc.setTextColor(0, 212, 170); // Teal
    doc.setFontSize(14);
    doc.text(`₹${safeCurrency((leadData as any).value)}`, 60, 128);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text('Current Stage:', 20, 138);
    doc.setTextColor(26, 35, 50);
    doc.text(safeStageLabel((leadData as any).stage), 60, 138);

    doc.setTextColor(100, 116, 139);
    doc.text('Priority:', 20, 148);
    doc.setTextColor(26, 35, 50);
    doc.text(safeStr((leadData as any).priority), 60, 148);

    // Interactions Section
    doc.setFontSize(16);
    doc.setTextColor(26, 35, 50);
    doc.text('Recent Interactions', 20, 165);

    doc.line(20, 168, 190, 168);

    doc.setFontSize(9);
    let yPos = 178;

    if (leadData.interactions && leadData.interactions.length > 0) {
      leadData.interactions.slice(0, 5).forEach((interaction: any) => {
        if (yPos > 270) return; // Avoid overflow

        doc.setTextColor(26, 35, 50);
        doc.setFontSize(10);
        doc.text(safeStr(interaction?.type).toUpperCase(), 20, yPos);

        doc.setFontSize(9);
        doc.setTextColor(100, 116, 139);
        const notes = safeStr(interaction?.notes);
        doc.text((notes.length > 70 ? notes.substring(0, 70) + '…' : notes) || '—', 20, yPos + 5);
        const when = interaction?.date || interaction?.createdAt;
        doc.text(when ? new Date(when).toLocaleDateString() : '—', 20, yPos + 10);

        yPos += 20;
      });
    } else {
      doc.setTextColor(100, 116, 139);
      doc.text('No interactions recorded', 20, yPos);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text('This is a confidential document generated by Lead Link CRM', 105, 280, { align: 'center' });
    doc.text('© 2026 Lead Link CRM', 105, 285, { align: 'center' });

    // Save the PDF
    const filenameBase = safeStr((leadData as any).company).trim().replace(/\s+/g, '_') || 'lead';
    doc.save(`${filenameBase}_Summary.pdf`);
  };

  if (loading) {
    return (
      <div className="flex" style={{ background: '#0B1120', minHeight: '100vh' }}>
        <Sidebar />
        <main className="flex-1 flex items-center justify-center" style={{ background: '#0B1120' }}>
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 mx-auto" style={{ border: '4px solid rgba(0,212,170,0.2)', borderTop: '4px solid #00D4AA' }}></div>
            <p className="mt-4" style={{ color: '#94A3B8' }}>Loading PDF preview...</p>
          </div>
        </main>
      </div>
    );
  }

  if (!leadData) {
    return (
      <div className="flex" style={{ background: '#0B1120', minHeight: '100vh' }}>
        <Sidebar />
        <main className="flex-1 flex items-center justify-center" style={{ background: '#0B1120' }}>
          <div className="text-center">
            <p className="text-lg" style={{ color: '#94A3B8' }}>Customer not found</p>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="flex flex-col md:flex-row h-screen overflow-hidden" style={{ background: '#0B1120', minHeight: '100vh' }}>
      <Sidebar />

      <main className="flex-1 min-w-0 overflow-auto" style={{ background: '#0B1120' }}>
        <div className="p-8">
          <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <Link
                to={`/customer/${id}`}
                className="p-2 rounded-lg transition-colors"
                style={{ background: 'rgba(148,163,184,0.1)' }}
              >
                <ArrowLeft className="w-5 h-5" style={{ color: '#F1F5F9' }} />
              </Link>
              <div>
                <h1 className="text-3xl font-bold" style={{ color: '#F1F5F9', fontFamily: 'Outfit, sans-serif' }}>Customer Summary PDF</h1>
                <p className="mt-1" style={{ color: '#64748B' }}>Preview and download customer report</p>
              </div>
            </div>
            <button
              onClick={handleDownload}
              className="px-6 py-3 rounded-lg font-medium transition-all flex items-center gap-2"
              style={{ background: 'linear-gradient(135deg, #00D4AA, #00B894)', color: '#0B1120', boxShadow: '0 4px 24px rgba(0, 212, 170, 0.25)' }}
            >
              <Download className="w-5 h-5" />
              Download PDF
            </button>
          </div>

          {/* PDF Preview (Mockup showing the white paper) */}
          <div className="rounded-xl shadow-lg mx-auto overflow-hidden border" style={{ maxWidth: '800px', background: '#F8FAFC', borderColor: 'rgba(148,163,184,0.1)' }}>
            <div className="p-12">
              {/* Header */}
              <div className="pb-6 mb-8" style={{ borderBottom: '2px solid #00D4AA' }}>
                <div className="flex items-start justify-between">
                  <div>
                    <h1 className="text-4xl font-bold mb-2" style={{ color: '#00D4AA' }}>Lead Link CRM</h1>
                    <p style={{ color: '#64748B' }}>Customer Relationship Management</p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm" style={{ color: '#64748B' }}>Report Date</p>
                    <p className="font-semibold" style={{ color: '#0F172A' }}>{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
                  </div>
                </div>
              </div>

              {/* Customer Information */}
              <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4 pb-2" style={{ color: '#0F172A', borderBottom: '1px solid #CBD5E1' }}>
                  Customer Information
                </h2>
                <div className="grid grid-cols-2 gap-6">
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Company Name</p>
                    <p className="font-semibold" style={{ color: '#0F172A' }}>{leadData.company}</p>
                  </div>
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Contact Person</p>
                    <p className="font-semibold" style={{ color: '#0F172A' }}>{leadData.contact}</p>
                  </div>
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Email Address</p>
                    <p className="font-semibold" style={{ color: '#0F172A' }}>{leadData.email}</p>
                  </div>
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Phone Number</p>
                    <p className="font-semibold" style={{ color: '#0F172A' }}>{leadData.phone || 'N/A'}</p>
                  </div>
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Lead Score</p>
                    <p className="font-semibold flex items-center gap-1" style={{ color: '#0F172A' }}>
                      <Star className="w-4 h-4 fill-current" style={{ color: '#EAB308' }} />
                      {leadData.leadScore}/100
                    </p>
                  </div>
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Current Stage</p>
                    <p className="font-semibold capitalize" style={{ color: '#0F172A' }}>{leadData.stage}</p>
                  </div>
                </div>
              </div>

              {/* Deal Information */}
              <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4 pb-2" style={{ color: '#0F172A', borderBottom: '1px solid #CBD5E1' }}>
                  Deal Information
                </h2>
                <div className="grid grid-cols-2 gap-6">
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Deal Value</p>
                    <p className="text-2xl font-bold" style={{ color: '#00D4AA' }}>₹{(Number((leadData as any).value) || 0).toLocaleString('en-IN')}</p>
                  </div>
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Priority</p>
                    <p className="font-semibold" style={{ color: '#0F172A' }}>{leadData.priority}</p>
                  </div>
                  <div>
                    <p className="text-sm mb-1" style={{ color: '#64748B' }}>Risk Status</p>
                    <p className="font-semibold uppercase" style={{ color: '#0F172A' }}>{leadData.risk || 'LOW'}</p>
                  </div>
                    <div>
                      <p className="text-sm mb-1" style={{ color: '#64748B' }}>Last Updated</p>
                      <p className="font-semibold" style={{ color: '#0F172A' }}>{leadData.lastInteraction ? new Date(leadData.lastInteraction).toLocaleDateString() : 'Never'}</p>
                    </div>
                </div>
              </div>

              {/* Interaction Summary */}
              <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4 pb-2" style={{ color: '#0F172A', borderBottom: '1px solid #CBD5E1' }}>
                  Recent Interactions
                </h2>
                <div className="space-y-4">
                  {leadData.interactions && leadData.interactions.length > 0 ? (
                    leadData.interactions.slice(0, 5).map((interaction: any, idx: number) => (
                      <div key={idx} className="flex gap-4 pb-4" style={{ borderBottom: '1px solid #E2E8F0' }}>
                        <div className="w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0" style={{
                          background: interaction.type === 'call' ? 'rgba(0, 212, 170, 0.15)' :
                            interaction.type === 'email' ? 'rgba(192, 132, 252, 0.15)' :
                              'rgba(245, 158, 11, 0.15)'
                        }}>
                          {interaction.type === 'call' ? <Phone className="w-5 h-5" style={{ color: '#00D4AA' }} /> :
                            interaction.type === 'email' ? <Mail className="w-5 h-5" style={{ color: '#C084FC' }} /> :
                              <Calendar className="w-5 h-5" style={{ color: '#F59E0B' }} />}
                        </div>
                        <div>
                          <p className="font-semibold capitalize" style={{ color: '#0F172A' }}>{interaction.type}</p>
                          <p className="text-sm mt-1" style={{ color: '#475569' }}>{interaction.notes || '—'}</p>
                          <p className="text-xs mt-1" style={{ color: '#64748B' }}>
                            {interaction?.date || interaction?.createdAt ? new Date(interaction.date || interaction.createdAt).toLocaleDateString() : '—'}
                          </p>
                        </div>
                      </div>
                    ))
                  ) : (
                    <p style={{ color: '#64748B' }}>No interactions recorded</p>
                  )}
                </div>
              </div>

              {/* Footer */}
              <div className="mt-12 pt-6 text-center" style={{ borderTop: '1px solid #CBD5E1' }}>
                <p className="text-sm" style={{ color: '#64748B' }}>
                  This is a confidential document generated by Lead Link CRM
                </p>
                <p className="text-sm mt-1" style={{ color: '#64748B' }}>
                  © 2026 Lead Link CRM
                </p>
              </div>
            </div>
          </div>

        </div>
      </main>
    </div>
  );
}
