import { useEffect, useState } from 'react';
import { Sidebar } from '../components/Sidebar';
import { useParams, Link } from 'react-router';
import { Download, ArrowLeft, Mail, Phone, Calendar, Star } from 'lucide-react';
import { useLeads } from '../contexts/LeadsContext';
import jsPDF from 'jspdf';

export default function PdfPreview() {
  const { id } = useParams();
  const { getLeadById } = useLeads();
  const [leadData, setLeadData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchLead = async () => {
      if (id) {
        try {
          const data = await getLeadById(parseInt(id));
          setLeadData(data);
        } catch (error) {
          console.error('Error fetching lead:', error);
        } finally {
          setLoading(false);
        }
      }
    };
    fetchLead();
  }, [id, getLeadById]);

  const handleDownload = () => {
    if (!leadData) return;

    const doc = new jsPDF();

    // Header
    doc.setFontSize(24);
    doc.setTextColor(37, 99, 235); // blue-600
    doc.text('CRM Pro', 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128); // gray-500
    doc.text('Customer Relationship Management', 20, 27);

    // Report Date
    doc.setFontSize(10);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 150, 20);

    // Customer Information Section
    doc.setFontSize(16);
    doc.setTextColor(17, 24, 39); // gray-900
    doc.text('Customer Information', 20, 45);

    doc.setDrawColor(209, 213, 219); // gray-300
    doc.line(20, 48, 190, 48);

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);

    doc.text('Company:', 20, 58);
    doc.setTextColor(17, 24, 39);
    doc.text(leadData.company, 60, 58);

    doc.setTextColor(107, 114, 128);
    doc.text('Contact:', 20, 68);
    doc.setTextColor(17, 24, 39);
    doc.text(leadData.contact, 60, 68);

    doc.setTextColor(107, 114, 128);
    doc.text('Email:', 20, 78);
    doc.setTextColor(17, 24, 39);
    doc.text(leadData.email, 60, 78);

    doc.setTextColor(107, 114, 128);
    doc.text('Lead Score:', 20, 88);
    doc.setTextColor(17, 24, 39);
    doc.text(`${leadData.leadScore}/100`, 60, 88);

    doc.setTextColor(107, 114, 128);
    doc.text('Risk Status:', 20, 98);
    doc.setTextColor(17, 24, 39);
    doc.text(leadData.risk ? leadData.risk.toUpperCase() : 'LOW', 60, 98);

    // Deal Information Section
    doc.setFontSize(16);
    doc.setTextColor(17, 24, 39);
    doc.text('Deal Information', 20, 115);

    doc.line(20, 118, 190, 118);

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);

    doc.text('Deal Value:', 20, 128);
    doc.setTextColor(34, 197, 94); // green-600
    doc.setFontSize(14);
    doc.text(`$${leadData.value.toLocaleString()}`, 60, 128);

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text('Current Stage:', 20, 138);
    doc.setTextColor(17, 24, 39);
    doc.text(leadData.stage.charAt(0).toUpperCase() + leadData.stage.slice(1), 60, 138);

    doc.setTextColor(107, 114, 128);
    doc.text('Priority:', 20, 148);
    doc.setTextColor(17, 24, 39);
    doc.text(leadData.priority, 60, 148);

    // Interactions Section
    doc.setFontSize(16);
    doc.setTextColor(17, 24, 39);
    doc.text('Recent Interactions', 20, 165);

    doc.line(20, 168, 190, 168);

    doc.setFontSize(9);
    let yPos = 178;

    if (leadData.interactions && leadData.interactions.length > 0) {
      leadData.interactions.slice(0, 5).forEach((interaction: any) => {
        if (yPos > 270) return; // Avoid overflow

        doc.setTextColor(17, 24, 39);
        doc.setFontSize(10);
        doc.text(interaction.type.toUpperCase(), 20, yPos);

        doc.setFontSize(9);
        doc.setTextColor(107, 114, 128);
        doc.text(interaction.notes.substring(0, 70) + '...', 20, yPos + 5);
        doc.text(new Date(interaction.timestamp).toLocaleDateString(), 20, yPos + 10);

        yPos += 20;
      });
    } else {
      doc.setTextColor(107, 114, 128);
      doc.text('No interactions recorded', 20, yPos);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text('This is a confidential document generated by CRM Pro', 105, 280, { align: 'center' });
    doc.text('© 2026 CRM Pro - College Mini Project', 105, 285, { align: 'center' });

    // Save the PDF
    doc.save(`${leadData.company.replace(/ /g, '_')}_Summary.pdf`);
  };

  if (loading) {
    return (
      <div className="flex">
        <Sidebar />
        <main className="flex-1 bg-gray-50 flex items-center justify-center">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
            <p className="mt-4 text-gray-600">Loading PDF preview...</p>
          </div>
        </main>
      </div>
    );
  }

  if (!leadData) {
    return (
      <div className="flex">
        <Sidebar />
        <main className="flex-1 bg-gray-50 flex items-center justify-center">
          <div className="text-center">
            <p className="text-lg text-gray-600">Customer not found</p>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="flex">
      <Sidebar />

      <main className="flex-1 bg-gray-50 overflow-auto">
        <div className="p-8">
          <div className="mb-8 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link
                to={`/customer/${id}`}
                className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
              >
                <ArrowLeft className="w-5 h-5 text-gray-600" />
              </Link>
              <div>
                <h1 className="text-3xl font-bold text-gray-900">Customer Summary PDF</h1>
                <p className="text-gray-600 mt-1">Preview and download customer report</p>
              </div>
            </div>
            <button
              onClick={handleDownload}
              className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 font-medium"
            >
              <Download className="w-5 h-5" />
              Download PDF
            </button>
          </div>

          {/* PDF Preview */}
          <div className="bg-white rounded-xl shadow-lg border border-gray-200 max-w-4xl mx-auto">
            <div className="p-12 bg-white">
              {/* Header */}
              <div className="border-b-2 border-blue-600 pb-6 mb-8">
                <div className="flex items-start justify-between">
                  <div>
                    <h1 className="text-4xl font-bold text-blue-600 mb-2">CRM Pro</h1>
                    <p className="text-gray-600">Customer Relationship Management</p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm text-gray-600">Report Date</p>
                    <p className="font-semibold text-gray-900">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
                  </div>
                </div>
              </div>

              {/* Customer Information */}
              <div className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-300">
                  Customer Information
                </h2>
                <div className="grid grid-cols-2 gap-6">
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Company Name</p>
                    <p className="font-semibold text-gray-900">{leadData.company}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Contact Person</p>
                    <p className="font-semibold text-gray-900">{leadData.contact}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Email Address</p>
                    <p className="font-semibold text-gray-900">{leadData.email}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Phone Number</p>
                    <p className="font-semibold text-gray-900">{leadData.phone || 'N/A'}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Lead Score</p>
                    <p className="font-semibold text-gray-900 flex items-center gap-1">
                      <Star className="w-4 h-4 text-yellow-500 fill-current" />
                      {leadData.leadScore}/100
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Current Stage</p>
                    <p className="font-semibold text-gray-900 capitalize">{leadData.stage}</p>
                  </div>
                </div>
              </div>

              {/* Deal Information */}
              <div className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-300">
                  Deal Information
                </h2>
                <div className="grid grid-cols-2 gap-6">
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Deal Value</p>
                    <p className="text-2xl font-bold text-green-600">${leadData.value.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Priority</p>
                    <p className="font-semibold text-gray-900">{leadData.priority}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Risk Status</p>
                    <p className="font-semibold text-gray-900 uppercase">{leadData.risk || 'LOW'}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Last Updated</p>
                    <p className="font-semibold text-gray-900">{new Date(leadData.lastInteraction).toLocaleDateString()}</p>
                  </div>
                </div>
              </div>

              {/* Interaction Summary */}
              <div className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-300">
                  Recent Interactions
                </h2>
                <div className="space-y-4">
                  {leadData.interactions && leadData.interactions.length > 0 ? (
                    leadData.interactions.slice(0, 5).map((interaction: any, idx: number) => (
                      <div key={idx} className="flex gap-4 pb-4 border-b border-gray-200">
                        <div className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 ${interaction.type === 'call' ? 'bg-blue-100' :
                          interaction.type === 'email' ? 'bg-purple-100' :
                            'bg-green-100'
                          }`}>
                          {interaction.type === 'call' ? <Phone className="w-5 h-5 text-blue-600" /> :
                            interaction.type === 'email' ? <Mail className="w-5 h-5 text-purple-600" /> :
                              <Calendar className="w-5 h-5 text-green-600" />}
                        </div>
                        <div>
                          <p className="font-semibold text-gray-900 capitalize">{interaction.type}</p>
                          <p className="text-sm text-gray-600 mt-1">{interaction.notes}</p>
                          <p className="text-xs text-gray-500 mt-1">{new Date(interaction.timestamp).toLocaleDateString()}</p>
                        </div>
                      </div>
                    ))
                  ) : (
                    <p className="text-gray-500">No interactions recorded</p>
                  )}
                </div>
              </div>

              {/* Footer */}
              <div className="mt-12 pt-6 border-t border-gray-300 text-center">
                <p className="text-sm text-gray-600">
                  This is a confidential document generated by CRM Pro
                </p>
                <p className="text-sm text-gray-600 mt-1">
                  © 2026 CRM Pro - College Mini Project
                </p>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="max-w-4xl mx-auto mt-6 flex gap-4 justify-center">
            <button
              onClick={handleDownload}
              className="bg-blue-600 text-white px-8 py-3 rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 font-medium"
            >
              <Download className="w-5 h-5" />
              Download PDF
            </button>
            <Link
              to={`/customer/${id}`}
              className="border-2 border-gray-300 text-gray-700 px-8 py-3 rounded-lg hover:bg-gray-50 transition-colors font-medium"
            >
              Back to Customer
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
