import React from 'react';
import { Layers } from 'lucide-react';
import { 
  ResponsiveContainer, 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  PieChart, 
  Pie, 
  Cell 
} from 'recharts';

interface ReportExportViewProps {
  data: any;
  filters: {
    period: string;
    label: string;
  };
  organizationName: string;
  generatedBy: string;
}

export const ReportExportView: React.FC<ReportExportViewProps> = ({ 
  data, 
  filters, 
  organizationName,
  generatedBy 
}) => {
  if (!data) return null;

  // Formatting timestamp
  const timestamp = new Date().toLocaleString('en-US', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true
  });

  // Calculate Metrics (Aligned with actual CRM data)
  const totalLeads = (data?.leadFlow?.new || 0) + (data?.leadFlow?.contacted || 0) + (data?.leadFlow?.interested || 0) + (data?.leadFlow?.converted || 0);
  const convertedLeads = data?.leadFlow?.converted || 0;
  const conversionRate = totalLeads > 0 ? ((convertedLeads / totalLeads) * 100).toFixed(1) : "0.0";
  const activeLeads = (data?.leadFlow?.contacted || 0) + (data?.leadFlow?.interested || 0);

  // Chart Colors (Professional Light Theme)
  const funnelData = [
    { name: 'New', value: data?.leadFlow?.new ?? 0, color: '#3b82f6' },
    { name: 'Contacted', value: data?.leadFlow?.contacted ?? 0, color: '#f59e0b' },
    { name: 'Interested', value: data?.leadFlow?.interested ?? 0, color: '#8b5cf6' },
    { name: 'Converted', value: data?.leadFlow?.converted ?? 0, color: '#10b981' },
  ];

  const taskData = [
    { name: 'Created', count: data?.taskTrends?.created ?? 0, fill: '#3b82f6' },
    { name: 'Completed', count: data?.taskTrends?.completed ?? 0, fill: '#10b981' },
  ];

  return (
    <div 
      id="report-export-container"
      className="bg-white text-slate-900 font-sans flex flex-col pointer-events-none absolute"
      style={{ 
        boxSizing: 'border-box',
        width: '794px',
        minHeight: '1123px',
        padding: '90px',
        opacity: 0.001,
        left: '-9999px',
        top: 0 
      }}
    >
      {/* 1. HEADER */}
      <header className="flex justify-between items-start mb-12">
        <div className="flex flex-col">
          <div className="flex items-center gap-2 mb-1">
            <Layers size={20} className="text-slate-800" />
            <span className="text-xl font-bold text-slate-800 leading-none">LeadLink</span>
          </div>
          <div className="text-sm font-bold text-slate-800">{organizationName}</div>
        </div>

        <div className="text-right flex flex-col items-end">
          <h1 className="text-2xl font-bold text-slate-900 mb-2">Overview Report</h1>
          <div className="text-sm text-slate-600 leading-relaxed text-right">
            Report Period: <strong>{filters.label}</strong><br />
            Generated On: {timestamp}<br />
            Generated By: {generatedBy}
          </div>
        </div>
      </header>

      {/* 2. SUMMARY (TEXTUAL BULLETS) */}
      <section className="mb-12">
        <h2 className="text-sm uppercase font-bold text-slate-900 mb-4">Summary</h2>
        <ul className="list-disc pl-5 text-sm text-slate-600 space-y-2">
          <li>A total of <strong>{totalLeads}</strong> leads were recorded during the selected period.</li>
          <li>The conversion rate is <strong>{conversionRate}%</strong>, indicating sales performance.</li>
          <li><strong>{activeLeads}</strong> leads are currently active in the pipeline.</li>
          <li>Task activity reflects operational trends based on created vs completed tasks.</li>
        </ul>
      </section>

      <div className="border-t border-slate-100 my-8" />

      {/* 3. EXECUTIVE METRICS (KPI) */}
      <section className="mb-12">
        <h2 className="text-sm uppercase font-bold text-slate-900 mb-4">Executive Metrics</h2>
        <div className="grid grid-cols-3 gap-6">
          <div className="border border-slate-200 rounded-md p-4 bg-white">
            <p className="text-xs text-slate-500 mb-1">Total Leads</p>
            <p className="text-xl font-bold text-slate-900">{totalLeads}</p>
          </div>
          <div className="border border-slate-200 rounded-md p-4 bg-white">
            <p className="text-xs text-slate-500 mb-1">Conversion Rate</p>
            <p className="text-xl font-bold text-slate-900">{conversionRate}%</p>
          </div>
          <div className="border border-slate-200 rounded-md p-4 bg-white">
            <p className="text-xs text-slate-500 mb-1">Active Pipeline</p>
            <p className="text-xl font-bold text-slate-900">{activeLeads}</p>
          </div>
        </div>
      </section>

      <div className="border-t border-slate-100 my-8" />

      {/* 4. ANALYTICS (CHARTS) */}
      <section className="mb-12">
        <h2 className="text-sm uppercase font-bold text-slate-900 mb-4">Analytics Overview</h2>
        <div className="grid grid-cols-2 gap-8">
          
          {/* Chart 1 */}
          <div className="flex flex-col">
            <div className="h-[220px] w-full bg-white mb-4">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={funnelData}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    paddingAngle={2}
                    dataKey="value"
                  >
                    {funnelData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip 
                    contentStyle={{ 
                      borderRadius: '4px', 
                      border: '1px solid #e2e8f0', 
                      boxShadow: 'none',
                      fontSize: '10px'
                    }} 
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
            
            <div className="grid grid-cols-2 gap-2 mb-2">
              {funnelData.map((item, idx) => (
                <div key={idx} className="flex justify-between items-center text-xs">
                  <div className="flex items-center gap-1.5">
                    <div className="w-2 h-2 rounded-full" style={{ backgroundColor: item.color }} />
                    <span className="text-slate-500">{item.name}</span>
                  </div>
                  <span className="text-slate-900 font-bold">{item.value}</span>
                </div>
              ))}
            </div>
            <p className="text-xs text-slate-500 text-center">Breakdown of Lead Distribution</p>
          </div>

          {/* Chart 2 */}
          <div className="flex flex-col">
            <div className="h-[220px] w-full bg-white mb-4">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart 
                  data={taskData} 
                  margin={{ top: 10, right: 10, left: -20, bottom: 0 }}
                >
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis 
                    dataKey="name" 
                    axisLine={false}
                    tickLine={false}
                    tick={{ fontSize: 10, fill: '#64748b' }}
                  />
                  <YAxis 
                    axisLine={false}
                    tickLine={false}
                    tick={{ fontSize: 10, fill: '#64748b' }}
                  />
                  <Tooltip 
                    cursor={{ fill: '#f8fafc' }}
                    contentStyle={{ 
                      borderRadius: '4px', 
                      border: '1px solid #e2e8f0', 
                      boxShadow: 'none',
                      fontSize: '10px'
                    }}
                  />
                  <Bar 
                    dataKey="count" 
                    radius={[2, 2, 0, 0]} 
                    barSize={40}
                  >
                    {taskData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.fill} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
            <p className="text-xs text-slate-500 text-center">Task Initiation vs. Resolution Volume</p>
          </div>

        </div>
      </section>

      {/* 5. FOOTER */}
      <footer className="mt-auto border-t border-slate-200 pt-6 flex justify-between items-center">
        <span className="text-xs text-slate-500">LeadLink CRM &ndash; Confidential</span>
        <span className="text-xs text-slate-500">Page 1 of 1</span>
      </footer>
    </div>
  );
};
